theme: minima
title: JRG blog
description: "Welcome to my blog!"
baseurl: "/blog_markdown" # el subdirectorio de tu sitio
url: "https://jrgil20.github.io" # la URL base de tu sitio
author: JrGil20
markdown: kramdown